### ISSUE TITLE
Workflow definition language

### ISSUE THREAD

**Issue by benfortuna** [ical4j/ical4j-actions#5]
A workflow consists of triggers (conditions) and actions (intents) that may be provided via a pluggable interface (e.g. service loader, etc.).

To define a workflow we can use a simple workflow language (e.g. yaml):

```yaml
# create task to send email notifications when defined in meetings (via VALARM)
trigger:
 - filter: 'concept=semcal:concept:event:meeting'
actions:
 - template: 'org.ical4j.actions.tasks.AlarmEmailNotifications'
```

```yaml
# create task to send meeting invites via defined transport (e.g. email)
trigger:
 - filter: 'concept=semcal:concept:event:meeting and status=new'
actions:
  - template: 'org.ical4j.actions.tasks.SendMeetingInvitations'
```
